/*
 * This file is generated by jOOQ.
*/
package com.lesson.boot.docs.jooq.generator.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TActivity implements Serializable {

    private static final long serialVersionUID = -1000537090;

    private Long    id;
    private String  bannerUrl;
    private String  name;
    private Integer sequence;
    private String  url;
    private Long    beginTime;
    private Long    endTime;
    private Byte    status;
    private Byte    type;
    private Long    countryId;
    private Integer appVersion;

    public TActivity() {}

    public TActivity(TActivity value) {
        this.id = value.id;
        this.bannerUrl = value.bannerUrl;
        this.name = value.name;
        this.sequence = value.sequence;
        this.url = value.url;
        this.beginTime = value.beginTime;
        this.endTime = value.endTime;
        this.status = value.status;
        this.type = value.type;
        this.countryId = value.countryId;
        this.appVersion = value.appVersion;
    }

    public TActivity(
        Long    id,
        String  bannerUrl,
        String  name,
        Integer sequence,
        String  url,
        Long    beginTime,
        Long    endTime,
        Byte    status,
        Byte    type,
        Long    countryId,
        Integer appVersion
    ) {
        this.id = id;
        this.bannerUrl = bannerUrl;
        this.name = name;
        this.sequence = sequence;
        this.url = url;
        this.beginTime = beginTime;
        this.endTime = endTime;
        this.status = status;
        this.type = type;
        this.countryId = countryId;
        this.appVersion = appVersion;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getBannerUrl() {
        return this.bannerUrl;
    }

    public void setBannerUrl(String bannerUrl) {
        this.bannerUrl = bannerUrl;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getSequence() {
        return this.sequence;
    }

    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Long getBeginTime() {
        return this.beginTime;
    }

    public void setBeginTime(Long beginTime) {
        this.beginTime = beginTime;
    }

    public Long getEndTime() {
        return this.endTime;
    }

    public void setEndTime(Long endTime) {
        this.endTime = endTime;
    }

    public Byte getStatus() {
        return this.status;
    }

    public void setStatus(Byte status) {
        this.status = status;
    }

    public Byte getType() {
        return this.type;
    }

    public void setType(Byte type) {
        this.type = type;
    }

    public Long getCountryId() {
        return this.countryId;
    }

    public void setCountryId(Long countryId) {
        this.countryId = countryId;
    }

    public Integer getAppVersion() {
        return this.appVersion;
    }

    public void setAppVersion(Integer appVersion) {
        this.appVersion = appVersion;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TActivity (");

        sb.append(id);
        sb.append(", ").append(bannerUrl);
        sb.append(", ").append(name);
        sb.append(", ").append(sequence);
        sb.append(", ").append(url);
        sb.append(", ").append(beginTime);
        sb.append(", ").append(endTime);
        sb.append(", ").append(status);
        sb.append(", ").append(type);
        sb.append(", ").append(countryId);
        sb.append(", ").append(appVersion);

        sb.append(")");
        return sb.toString();
    }
}
