/*
 * This file is generated by jOOQ.
*/
package com.lesson.boot.docs.jooq.generator.tables.records;


import com.lesson.boot.docs.jooq.generator.tables.TActivity;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TActivityRecord extends UpdatableRecordImpl<TActivityRecord> implements Record11<Long, String, String, Integer, String, Long, Long, Byte, Byte, Long, Integer> {

    private static final long serialVersionUID = -1358240096;

    /**
     * Setter for <code>pandadb.t_activity.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>pandadb.t_activity.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>pandadb.t_activity.banner_url</code>.
     */
    public void setBannerUrl(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pandadb.t_activity.banner_url</code>.
     */
    public String getBannerUrl() {
        return (String) get(1);
    }

    /**
     * Setter for <code>pandadb.t_activity.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>pandadb.t_activity.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>pandadb.t_activity.sequence</code>.
     */
    public void setSequence(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>pandadb.t_activity.sequence</code>.
     */
    public Integer getSequence() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>pandadb.t_activity.url</code>.
     */
    public void setUrl(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>pandadb.t_activity.url</code>.
     */
    public String getUrl() {
        return (String) get(4);
    }

    /**
     * Setter for <code>pandadb.t_activity.begin_time</code>.
     */
    public void setBeginTime(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>pandadb.t_activity.begin_time</code>.
     */
    public Long getBeginTime() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>pandadb.t_activity.end_time</code>.
     */
    public void setEndTime(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>pandadb.t_activity.end_time</code>.
     */
    public Long getEndTime() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>pandadb.t_activity.status</code>.
     */
    public void setStatus(Byte value) {
        set(7, value);
    }

    /**
     * Getter for <code>pandadb.t_activity.status</code>.
     */
    public Byte getStatus() {
        return (Byte) get(7);
    }

    /**
     * Setter for <code>pandadb.t_activity.type</code>.
     */
    public void setType(Byte value) {
        set(8, value);
    }

    /**
     * Getter for <code>pandadb.t_activity.type</code>.
     */
    public Byte getType() {
        return (Byte) get(8);
    }

    /**
     * Setter for <code>pandadb.t_activity.country_id</code>.
     */
    public void setCountryId(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>pandadb.t_activity.country_id</code>.
     */
    public Long getCountryId() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>pandadb.t_activity.app_version</code>. 支撑app版本
     */
    public void setAppVersion(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>pandadb.t_activity.app_version</code>. 支撑app版本
     */
    public Integer getAppVersion() {
        return (Integer) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Long, String, String, Integer, String, Long, Long, Byte, Byte, Long, Integer> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Long, String, String, Integer, String, Long, Long, Byte, Byte, Long, Integer> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return TActivity.T_ACTIVITY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TActivity.T_ACTIVITY.BANNER_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TActivity.T_ACTIVITY.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return TActivity.T_ACTIVITY.SEQUENCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TActivity.T_ACTIVITY.URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return TActivity.T_ACTIVITY.BEGIN_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return TActivity.T_ACTIVITY.END_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field8() {
        return TActivity.T_ACTIVITY.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field9() {
        return TActivity.T_ACTIVITY.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field10() {
        return TActivity.T_ACTIVITY.COUNTRY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return TActivity.T_ACTIVITY.APP_VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getBannerUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getSequence();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component6() {
        return getBeginTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component7() {
        return getEndTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component8() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component9() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component10() {
        return getCountryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component11() {
        return getAppVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getBannerUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getSequence();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getBeginTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getEndTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value8() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value9() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value10() {
        return getCountryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getAppVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TActivityRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TActivityRecord value2(String value) {
        setBannerUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TActivityRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TActivityRecord value4(Integer value) {
        setSequence(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TActivityRecord value5(String value) {
        setUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TActivityRecord value6(Long value) {
        setBeginTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TActivityRecord value7(Long value) {
        setEndTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TActivityRecord value8(Byte value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TActivityRecord value9(Byte value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TActivityRecord value10(Long value) {
        setCountryId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TActivityRecord value11(Integer value) {
        setAppVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TActivityRecord values(Long value1, String value2, String value3, Integer value4, String value5, Long value6, Long value7, Byte value8, Byte value9, Long value10, Integer value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TActivityRecord
     */
    public TActivityRecord() {
        super(TActivity.T_ACTIVITY);
    }

    /**
     * Create a detached, initialised TActivityRecord
     */
    public TActivityRecord(Long id, String bannerUrl, String name, Integer sequence, String url, Long beginTime, Long endTime, Byte status, Byte type, Long countryId, Integer appVersion) {
        super(TActivity.T_ACTIVITY);

        set(0, id);
        set(1, bannerUrl);
        set(2, name);
        set(3, sequence);
        set(4, url);
        set(5, beginTime);
        set(6, endTime);
        set(7, status);
        set(8, type);
        set(9, countryId);
        set(10, appVersion);
    }
}
