/*
 * This file is generated by jOOQ.
*/
package com.lesson.boot.docs.jooq.generator;


import com.lesson.boot.docs.jooq.generator.tables.TActivity;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>pandadb</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index T_ACTIVITY_BEGIN_TIME = Indexes0.T_ACTIVITY_BEGIN_TIME;
    public static final Index T_ACTIVITY_END_TIME = Indexes0.T_ACTIVITY_END_TIME;
    public static final Index T_ACTIVITY_PRIMARY = Indexes0.T_ACTIVITY_PRIMARY;
    public static final Index T_ACTIVITY_STATUS = Indexes0.T_ACTIVITY_STATUS;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index T_ACTIVITY_BEGIN_TIME = Internal.createIndex("begin_time", TActivity.T_ACTIVITY, new OrderField[] { TActivity.T_ACTIVITY.BEGIN_TIME }, false);
        public static Index T_ACTIVITY_END_TIME = Internal.createIndex("end_time", TActivity.T_ACTIVITY, new OrderField[] { TActivity.T_ACTIVITY.END_TIME }, false);
        public static Index T_ACTIVITY_PRIMARY = Internal.createIndex("PRIMARY", TActivity.T_ACTIVITY, new OrderField[] { TActivity.T_ACTIVITY.ID }, true);
        public static Index T_ACTIVITY_STATUS = Internal.createIndex("status", TActivity.T_ACTIVITY, new OrderField[] { TActivity.T_ACTIVITY.STATUS }, false);
    }
}
