/*
 * This file is generated by jOOQ.
*/
package com.lesson.boot.docs.jooq.generator;


import com.lesson.boot.docs.jooq.generator.tables.TActivity;
import com.lesson.boot.docs.jooq.generator.tables.records.TActivityRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>pandadb</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<TActivityRecord, Long> IDENTITY_T_ACTIVITY = Identities0.IDENTITY_T_ACTIVITY;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<TActivityRecord> KEY_T_ACTIVITY_PRIMARY = UniqueKeys0.KEY_T_ACTIVITY_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<TActivityRecord, Long> IDENTITY_T_ACTIVITY = Internal.createIdentity(TActivity.T_ACTIVITY, TActivity.T_ACTIVITY.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<TActivityRecord> KEY_T_ACTIVITY_PRIMARY = Internal.createUniqueKey(TActivity.T_ACTIVITY, "KEY_t_activity_PRIMARY", TActivity.T_ACTIVITY.ID);
    }
}
