/*
 * This file is generated by jOOQ.
*/
package com.lesson.boot.docs.jooq.generator;


import com.lesson.boot.docs.jooq.generator.tables.TActivity;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Pandadb extends SchemaImpl {

    private static final long serialVersionUID = -787038478;

    /**
     * The reference instance of <code>pandadb</code>
     */
    public static final Pandadb PANDADB = new Pandadb();

    /**
     * The table <code>pandadb.t_activity</code>.
     */
    public final TActivity T_ACTIVITY = com.lesson.boot.docs.jooq.generator.tables.TActivity.T_ACTIVITY;

    /**
     * No further instances allowed
     */
    private Pandadb() {
        super("pandadb", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            TActivity.T_ACTIVITY);
    }
}
