/*
 * This file is generated by jOOQ.
*/
package com.lesson.boot.docs.jooq.generator;


import com.lesson.boot.docs.jooq.generator.tables.TActivity;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in pandadb
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>pandadb.t_activity</code>.
     */
    public static final TActivity T_ACTIVITY = com.lesson.boot.docs.jooq.generator.tables.TActivity.T_ACTIVITY;
}
